name: dbt CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-databricks

      - name: Install dependencies
        run: |
          dbt deps

      - name: Run dbt models (DEV)
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          dbt run --target dev

      - name: Run dbt tests
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          dbt test --target dev
